name: Build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install wine
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install wine32:i386 wine
      - name: wine hello
        run: wine cmd /c "echo hello"
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
