name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: [self-hosted, '${{ github.repository }}']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Wait
        run: sleep 30s
