name: Build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install wine
        run: sudo apt-get install -y wine64 python3 msitools ca-certificates winbind
      - name: Clone tdesktop
        run: git clone https://github.com/telegramdesktop/tdesktop.git --recursive
      - name: Clone msvc-wine
        run: git clone https://github.com/mstorsjo/msvc-wine.git
      - name: Setup MSVC
        run: |
          msvc-wine/vsdownload.py --dest ~/msvc-wine/opt/msvc --accept-license
          msvc-wine/install.sh ~/msvc-wine/opt/msvc
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
