name: Build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Clone tdesktop
        run: git clone https://github.com/telegramdesktop/tdesktop.git --recursive
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
