name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        id: [1, 2, 3]
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Echo
        run: |
          cat /aaaa || true
          echo "is there?"
          echo "b" > /aaaa
          cat /aaaa
          echo "there is."
      - name: Wait
        run: |
          echo ${{ matrix.id }}
