name: check

on:
  workflow_dispatch:

jobs:
  check-targets-matrix:
    runs-on: ubuntu-latest
    outputs:
      targets_matrix: ${{ steps.gen-matrix.outputs.targets_matrix }}
    steps:
    - name: Install Rust nightly
      run: rustup toolchain install nightly
    - name: Generate all tier 1 and tier 2 targets matrix
      id: gen-matrix
      run: |
        TARGETS=$(rustc +nightly --print all-target-specs-json -Z unstable-options \
          | jq -c "map_values(.metadata.tier) \
            | to_entries \
            | map({tier: .value, target: .key} \
            | select(.tier == 1 or .tier == 2)) \
            | sort_by(.tier)")
        echo "targets_matrix='$TARGETS'" >> "$GITHUB_OUTPUT"

  check-targets:
    needs: check-targets-matrix
    strategy:
      fail-fast: false
      matrix:
        target: [{"tier":1,"target":"test"}]
        # target: ${{ fromJSON(needs.check-targets-matrix.outputs.targets_matrix) }}
    runs-on: 'ubuntu-latest'
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Disable bench dependencies
      run: ./.github/workflows/disable-bench-deps.sh
    - name: Install dependencies
      run: sudo bash ./.github/workflows/install-deps.sh
    - name: Install Rust tier ${{ matrix.tier }} target ${{ matrix.target }}
      run: rustup target add ${{ matrix.target }}
    - name: Restore cargo caches
      uses: Swatinem/rust-cache@v2
    - name: Run check for tier ${{ matrix.tier }} target ${{ matrix.target }}
      run: cargo check --all-features --target ${{ matrix.target }}
