name: CI

on:
  push:

  pull_request:

  workflow_dispatch:

env:

defaults:
  run:
    shell: bash

jobs:
  bench:
    strategy:
      fail-fast: false
    runs-on: 'ubuntu-latest'
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Get previous workflow runs
      id: previous_runs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { data: runs } = await github.actions.listWorkflowRuns({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: context.workflow,
          });
          console.log(runs);
