name: CI

on:
  push:
    paths-ignore:
      - '**.md'
      - 'LICENSE'

  pull_request:
    paths-ignore:
      - '**.md'
      - 'LICENSE'

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  # When updating this, also update:
  # - src/lib.rs
  # - Cargo.toml
  # - README.md
  rust_minver: 1.56.0

defaults:
  run:
    shell: bash

jobs:
  bench:
    strategy:
      fail-fast: false
    runs-on: 'ubuntu-latest'
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Disable bench dependencies
      run: ./.github/workflows/disable-bench-deps.sh
    - name: Install Rust nightly
      run: rustup toolchain install nightly
    - name: Restore cargo caches
      uses: Swatinem/rust-cache@v2
    - name: Run benchmark
      run: cargo +nightly bench --features "multi-thread,runtime-pattern" --bench spdlog_rs | tee bench-result.txt
    - name: Discard irrelevant changes
      run: git checkout -- spdlog/Cargo.toml
    - name: Process results
      uses: benchmark-action/github-action-benchmark@v1
      with:
        name: spdlog-rs on Linux
        tool: cargo
        output-file-path: bench-result.txt
        benchmark-data-dir-path: docs/dev/bench
        github-token: ${{ secrets.GITHUB_TOKEN }}
        summary-always: true
        comment-on-alert: true
        alert-comment-cc-users: '@SpriteOvO'
    - name: Deploy results to GitHub Pages
      if: github.event_name != 'pull_request'
      run: git push 'https://SpriteOvO:${{ secrets.GITHUB_TOKEN }}@github.com/SpriteOvO/github-actions-test.git' gh-pages:gh-pages
