name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  bench:
    strategy:
      fail-fast: false
    runs-on: 'ubuntu-latest'
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Get previous workflow runs
      id: previous_runs
      uses: actions/github-script@v7
      with:
        script: |
          const data = await github.rest.actions.listWorkflowRuns({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: "ci.yml",
          });
          console.log(data);
