name: metrics

on:
  schedule: [{cron: "0 */1 * * *"}]
  workflow_dispatch:
  push:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: ci-metrics
          template: classic
          config_timezone: Asia/Shanghai
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_colors: github
          plugin_languages_threshold: 0%
          plugin_languages_indepth: no
          plugin_languages_recent_load: 300
          plugin_languages_recent_days: 14
          plugin_notable: yes
          plugin_notable_repositories: no

