name: RV

on:
  push:
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  rv:
    strategy:
      fail-fast: false
    runs-on:
      - riscv-builders
      - soc-spacemit-k1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Neofetch
        run: neofetch
