name: Scheduled build

on:
  schedule:
    - cron: "3 * * * *"

defaults:
  run:
    shell: bash

env:
  build_workflow: .github/workflows/build.yml

jobs:
  last-run:
    runs-on: 'ubuntu-latest'
    outputs:
      conclusion: ${{ steps.previous-runs.outputs.result }}
    steps:
      - name: Get previous workflow runs
        id: previous-runs
        uses: actions/github-script@v7
        with:
          script: |
            const { data } = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: '${{ env.build_workflow }}',
            })
            const previous_runs = data.workflow_runs
              .filter(run => run.head_branch === '${{ github.ref_name }}' && run.status === 'completed')
            return previous_runs[0].conclusion
  build:
    needs: last-run
    if: ${{ needs.last-run.outputs.conclusion }} == 'success'
    uses: ${{ env.build_workflow }}
