name: Scheduled build

on:
  workflow_dispatch:
  schedule:
    - cron: "3 * * * *"

defaults:
  run:
    shell: bash

jobs:
  last-run:
    runs-on: 'ubuntu-latest'
    outputs:
      conclusion: ${{ steps.previous-runs.outputs.result }}
    steps:
      - name: Get previous workflow runs
        id: previous-runs
        uses: actions/github-script@v7
        with:
          script: |
            const write_summary = async (text: string) => {
              const fs = require('fs')
              await fs.writeFile(process.env['GITHUB_STEP_SUMMARY'], text, err => {
                console.log(err)
                process.exit(1)
              })
            }

            const { data } = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'build.yml',
            })
            const all_runs = data.workflow_runs
            const previous_runs = all_runs
              .filter(run => run.head_branch === '${{ github.ref_name }}' && run.status === 'completed')


            return previous_runs[0].conclusion
  build:
    needs: last-run
    if: ${{ needs.last-run.outputs.conclusion }} == 'success'
    uses: ./.github/workflows/build.yml
