name: Scheduled build

on:
  workflow_dispatch:
  schedule:
    - cron: "3 * * * *"

defaults:
  run:
    shell: bash

jobs:
  previous-runs:
    runs-on: 'ubuntu-latest'
    outputs:
      last-conclusion: ${{ steps.previous-runs.outputs.result }}
    steps:
      - name: Get previous workflow runs
        id: previous-runs
        uses: actions/github-script@v7
        with:
          script: |
            const write_summary = async text => {
              const fs = require('fs')
              await fs.appendFile(process.env['GITHUB_STEP_SUMMARY'], text, err => {
                if (err) {
                  console.error(`failed to write summary: ${err}`)
                  process.exit(1)
                }
              })
            }

            const { data } = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'build.yml',
            })
            const all_runs = data.workflow_runs
            const previous_runs = all_runs
              .filter(run => run.head_branch === '${{ github.ref_name }}' && run.status === 'completed')

            await write_summary('The last completed workflow run\n')
            await write_summary(`\`\`\`json\n${JSON.stringify(previous_runs[0], null, 4)}\n\`\`\`\n`)
            await write_summary('All workflow runs\n')
            await write_summary(`\`\`\`json\n${JSON.stringify(all_runs, null, 4)}\n\`\`\`\n`)

            return previous_runs[0].conclusion
  build:
    needs: previous-runs
    if: ${{ needs.previous-runs.outputs.last-conclusion }} == 'success'
    uses: ./.github/workflows/build.yml
