name: sync

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Fetch upstream
        run: |
          git remote add tdesktop https://github.com/telegramdesktop/tdesktop.git
          git fetch tdesktop dev
          git checkout -B tdesktop tdesktop/dev
      - name: Commit sync commit
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

          jq -n --arg upstream_commit $(git rev-parse HEAD) '$ARGS.named' > .temp
          mv .github ._github

          git add --all
          git commit "Synchronize with upstream"
      - name: Push to origin
        run: git push origin --force
